

const KEY_EVENT = "events"
const KEY_RACE = "races"
const KEY_MEMBERS = "members"
const KEY_EVENT_INDEX = "eventIndex"
const KEY_RACE_INDEX = "raceIndex"

let events = [];
let races = [];
let members = [];
let raceIndex = "";
let eventIndex = "";


function getLocalStorage(keyIn) {
    return JSON.parse(localStorage.getItem(keyIn));
}

function setLocalStorage(keyToSet, data) {
    let JSONConverted = JSON.stringify(data)
    return localStorage.setItem(keyToSet, JSONConverted)
}

//Setting initial local storage on start up 
//Arrays
if (getLocalStorage(KEY_MEMBERS) != null) {
    members = getLocalStorage(KEY_MEMBERS);
} else {
    setLocalStorage(KEY_MEMBERS, "");
}

//Indicies
if (getLocalStorage(KEY_EVENT_INDEX) != null) {
    eventIndex = getLocalStorage(KEY_EVENT_INDEX);
} else {
    setLocalStorage(KEY_EVENT_INDEX, "");
}

if (getLocalStorage(KEY_RACE_INDEX) != null) {
    raceIndex = getLocalStorage(KEY_RACE_INDEX);
} else {
    setLocalStorage(KEY_RACE_INDEX, "");
}


/*** Member Data ***/
const data = [
    {
      _firstName: "Anne",
      _surname: "King",
      _gender: "F",
      _fullName: "Anne King",
      _left: "Anne King",
      _right: "",
      _sweep: "",
      _drummer: "",
      _weight: "77.2",
      _preference: "_left",
      _division: "C",
      _gender: "F",
      _noOfRaces: "2",
      _sweepOrDrummerRaces: "0",
      _paddling: "2",
      Reserve: ""
    },
    {
      _firstName: "Annette",
      _surname: "Chappel",
      _gender: "F",
      _fullName: "Annette Chappel",
      _left: "Annette Chappel",
      _right: "Annette Chappel",
      _sweep: "",
      _drummer: "Annette Chappel",
      _weight: "60.4",
      _preference: "None",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "3",
      _sweepOrDrummerRaces: "0",
      _paddling: "3",
      Reserve: ""
    },
    {
      _firstName: "Annie",
      _surname: "Coates",
      _gender: "F",
      _fullName: "Annie Coates",
      _left: "Annie Coates",
      _right: "Annie Coates",
      _sweep: "",
      _drummer: "Annie Coates",
      _weight: "59.2",
      _preference: "_right",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "1",
      _sweepOrDrummerRaces: "0",
      _paddling: "1",
      Reserve: ""
    },
    {
      _firstName: "Beverley",
      _surname: "Davison",
      _gender: "F",
      _fullName: "Beverley Davison",
      _left: "Beverley Davison",
      _right: "Beverley Davison",
      _sweep: "",
      _drummer: "Beverley Davison",
      _weight: "100.0",
      _preference: "None",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Catherine",
      _surname: "Riddoch",
      _gender: "F",
      _fullName: "Catherine Riddoch",
      _left: "Catherine Riddoch",
      _right: "Catherine Riddoch",
      _sweep: "",
      _drummer: "",
      _weight: "89.1",
      _preference: "None",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Cathy",
      _surname: "Urie",
      _gender: "F",
      _fullName: "Cathy Urie",
      _left: "Cathy Urie",
      _right: "Cathy Urie",
      _sweep: "",
      _drummer: "",
      _weight: "88.3",
      _preference: "_right",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "2",
      _sweepOrDrummerRaces: "0",
      _paddling: "2",
      Reserve: ""
    },
    {
      _firstName: "Christel",
      _surname: "Hendrieckx",
      _gender: "F",
      _fullName: "Christel Hendrieckx",
      _left: "Christel Hendrieckx",
      _right: "Christel Hendrieckx",
      _sweep: "",
      _drummer: "",
      _weight: "56.5",
      _preference: "None",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "1",
      _sweepOrDrummerRaces: "0",
      _paddling: "1",
      Reserve: ""
    },
    {
      _firstName: "Claire",
      _surname: "Robinson",
      _gender: "F",
      _fullName: "Claire Robinson",
      _left: "Claire Robinson",
      _right: "",
      _sweep: "",
      _drummer: "Claire Robinson",
      _weight: "64.2",
      _preference: "_left",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Colleen",
      _surname: "Sells",
      _gender: "F",
      _fullName: "Colleen Sells",
      _left: "Colleen Sells",
      _right: "Colleen Sells",
      _sweep: "",
      _drummer: "Colleen Sells",
      _weight: "58.0",
      _preference: "None",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Elizabeth",
      _surname: "Liston",
      _gender: "F",
      _fullName: "Elizabeth Liston",
      _left: "Elizabeth Liston",
      _right: "Elizabeth Liston",
      _sweep: "",
      _drummer: "",
      _weight: "",
      _preference: "_right",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Jan",
      _surname: "Hagston",
      _gender: "F",
      _fullName: "Jan Hagston",
      _left: "Jan Hagston",
      _right: "Jan Hagston",
      _sweep: "",
      _drummer: "",
      _weight: "67.0",
      _preference: "_right",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Janet",
      _surname: "Buckley",
      _gender: "F",
      _fullName: "Janet Buckley",
      _left: "Janet Buckley",
      _right: "Janet Buckley",
      _sweep: "Janet Buckley",
      _drummer: "Janet Buckley",
      _weight: "59.7",
      _preference: "None",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Jennifer",
      _surname: "Atkins",
      _gender: "F",
      _fullName: "Jennifer Atkins",
      _left: "Jennifer Atkins",
      _right: "Jennifer Atkins",
      _sweep: "",
      _drummer: "",
      _weight: "73.5",
      _preference: "None",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Jennifer",
      _surname: "Donnelly",
      _gender: "F",
      _fullName: "Jennifer Donnelly",
      _left: "Jennifer Donnelly",
      _right: "Jennifer Donnelly",
      _sweep: "",
      _drummer: "",
      _weight: "94.7",
      _preference: "_right",
      _division: "A",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Jenny",
      _surname: "Britt",
      _gender: "F",
      _fullName: "Jenny Britt",
      _left: "Jenny Britt",
      _right: "Jenny Britt",
      _sweep: "",
      _drummer: "",
      _weight: "60.9",
      _preference: "_right",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Jenny",
      _surname: "Gibson",
      _gender: "F",
      _fullName: "Jenny Gibson",
      _left: "Jenny Gibson",
      _right: "Jenny Gibson",
      _sweep: "Jenny Gibson",
      _drummer: "Jenny Gibson",
      _weight: "52.4",
      _preference: "_right",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Jenny",
      _surname: "Walsh",
      _gender: "F",
      _fullName: "Jenny Walsh",
      _left: "Jenny Walsh",
      _right: "Jenny Walsh",
      _sweep: "",
      _drummer: "Jenny Walsh",
      _weight: "67.7",
      _preference: "None",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Jill",
      _surname: "Hicks",
      _gender: "F",
      _fullName: "Jill Hicks",
      _left: "Jill Hicks",
      _right: "",
      _sweep: "Jill Hicks",
      _drummer: "Jill Hicks",
      _weight: "61.8",
      _preference: "_left",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Lili",
      _surname: "Chan",
      _gender: "F",
      _fullName: "Lili Chan",
      _left: "Lili Chan",
      _right: "Lili Chan",
      _sweep: "",
      _drummer: "",
      _weight: "61.4",
      _preference: "_left",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Lisa",
      _surname: "Burns",
      _gender: "F",
      _fullName: "Lisa Burns",
      _left: "Lisa Burns",
      _right: "Lisa Burns",
      _sweep: "",
      _drummer: "Lisa Burns",
      _weight: "66.0",
      _preference: "_right",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Lorna",
      _surname: "Williams",
      _gender: "F",
      _fullName: "Lorna Williams",
      _left: "Lorna Williams",
      _right: "Lorna Williams",
      _sweep: "",
      _drummer: "",
      _weight: "",
      _preference: "None",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Marianne",
      _surname: "Clarke",
      _gender: "F",
      _fullName: "Marianne Clarke",
      _left: "Marianne Clarke",
      _right: "Marianne Clarke",
      _sweep: "",
      _drummer: "Marianne Clarke",
      _weight: "53.5",
      _preference: "None",
      _division: "B",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Margaret",
      _surname: "Birrell",
      _gender: "F",
      _fullName: "Margaret Birrell",
      _left: "Margaret Birrell",
      _right: "Margaret Birrell",
      _sweep: "",
      _drummer: "",
      _weight: "100.0",
      _preference: "None",
      _division: "A",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Nikki",
      _surname: "McKay",
      _gender: "F",
      _fullName: "Nikki McKay",
      _left: "Nikki McKay",
      _right: "Nikki McKay",
      _sweep: "",
      _drummer: "",
      _weight: "80.0",
      _preference: "None",
      _division: "B",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Philippa",
      _surname: "McLean",
      _gender: "F",
      _fullName: "Philippa McLean",
      _left: "Philippa McLean",
      _right: "Philippa McLean",
      _sweep: "",
      _drummer: "Philippa McLean",
      _weight: "60.0",
      _preference: "None",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Rhonda",
      _surname: "Jacobs",
      _gender: "F",
      _fullName: "Rhonda Jacobs",
      _left: "Rhonda Jacobs",
      _right: "Rhonda Jacobs",
      _sweep: "",
      _drummer: "Rhonda Jacobs",
      _weight: "68.4",
      _preference: "_right",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Ruth",
      _surname: "Gallant",
      _gender: "F",
      _fullName: "Ruth Gallant",
      _left: "Ruth Gallant",
      _right: "Ruth Gallant",
      _sweep: "",
      _drummer: "Ruth Gallant",
      _weight: "58.0",
      _preference: "None",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Sharon",
      _surname: "Higgins",
      _gender: "F",
      _fullName: "Sharon Higgins",
      _left: "Sharon Higgins",
      _right: "Sharon Higgins",
      _sweep: "",
      _drummer: "",
      _weight: "55.0",
      _preference: "_right",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Solange",
      _surname: "Rossi",
      _gender: "F",
      _fullName: "Solange Rossi",
      _left: "Solange Rossi",
      _right: "Solange Rossi",
      _sweep: "",
      _drummer: "",
      _weight: "85.0",
      _preference: "_right",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Sue",
      _surname: "Burdon-Jones",
      _gender: "F",
      _fullName: "Sue Burdon-Jones",
      _left: "Sue Burdon-Jones",
      _right: "Sue Burdon-Jones",
      _sweep: "",
      _drummer: "",
      _weight: "65.5",
      _preference: "None",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Teresa",
      _surname: "Pertzel",
      _gender: "F",
      _fullName: "Teresa Pertzel",
      _left: "Teresa Pertzel",
      _right: "Teresa Pertzel",
      _sweep: "",
      _drummer: "",
      _weight: "100.0",
      _preference: "None",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Therese",
      _surname: "Williams",
      _gender: "F",
      _fullName: "Therese Williams",
      _left: "Therese Williams",
      _right: "Therese Williams",
      _sweep: "",
      _drummer: "",
      _weight: "100.0",
      _preference: "None",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Vicki",
      _surname: "Shannon",
      _gender: "F",
      _fullName: "Vicki Shannon",
      _left: "Vicki Shannon",
      _right: "Vicki Shannon",
      _sweep: "Vicki Shannon",
      _drummer: "Vicki Shannon",
      _weight: "66.9",
      _preference: "_left",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Vivienne",
      _surname: "Halat",
      _gender: "F",
      _fullName: "Vivienne Halat",
      _left: "Vivienne Halat",
      _right: "Vivienne Halat",
      _sweep: "",
      _drummer: "",
      _weight: "60.0",
      _preference: "_right",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "1",
      _sweepOrDrummerRaces: "0",
      _paddling: "1",
      Reserve: ""
    },
    {
      _firstName: "Zonda",
      _surname: "Lynn",
      _gender: "F",
      _fullName: "Zonda Lynn",
      _left: "Zonda Lynn",
      _right: "Zonda Lynn",
      _sweep: "",
      _drummer: "",
      _weight: "90.6",
      _preference: "_left",
      _division: "C",
      _gender: "F",
      Regatta: "Yes",
      Men: " ",
      Women: "Yes",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Adrian",
      _surname: "Stephens",
      _gender: "M",
      _fullName: "Adrian Stephens",
      _left: "Adrian Stephens",
      _right: "",
      _sweep: "",
      _drummer: "",
      _weight: "97.3",
      _preference: "_left",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Alex",
      _surname: "Ang",
      _gender: "M",
      _fullName: "Alex Ang",
      _left: "Alex Ang",
      _right: "Alex Ang",
      _sweep: "",
      _drummer: "",
      _weight: "100.0",
      _preference: "None",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Alan",
      _surname: "Blackman",
      _gender: "M",
      _fullName: "Alan Blackman",
      _left: "Alan Blackman",
      _right: "Alan Blackman",
      _sweep: "",
      _drummer: "",
      _weight: "100.0",
      _preference: "None",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Ben",
      _surname: "Goldman",
      _gender: "M",
      _fullName: "Ben Goldman",
      _left: "Ben Goldman",
      _right: "Ben Goldman",
      _sweep: "",
      _drummer: "",
      _weight: "81.9",
      _preference: "_right",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "David",
      _surname: "McLatchie",
      _gender: "M",
      _fullName: "David McLatchie",
      _left: "David McLatchie",
      _right: "David McLatchie",
      _sweep: "",
      _drummer: "",
      _weight: "100.0",
      _preference: "None",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "David",
      _surname: "Nairn",
      _gender: "M",
      _fullName: "David Nairn",
      _left: "David Nairn",
      _right: "David Nairn",
      _sweep: "David Nairn",
      _drummer: "",
      _weight: "82.8",
      _preference: "_right",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Gordon",
      _surname: "Tribbick",
      _gender: "M",
      _fullName: "Gordon Tribbick",
      _left: "Gordon Tribbick",
      _right: "Gordon Tribbick",
      _sweep: "",
      _drummer: "",
      _weight: "80.0",
      _preference: "_right",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Ian",
      _surname: "Norman",
      _gender: "M",
      _fullName: "Ian Norman",
      _left: "Ian Norman",
      _right: "",
      _sweep: "Ian Norman",
      _drummer: "",
      _weight: "",
      _preference: "_right",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Jeff",
      _surname: "Saunders",
      _gender: "M",
      _fullName: "Jeff Saunders",
      _left: "Jeff Saunders",
      _right: "Jeff Saunders",
      _sweep: "Jeff Saunders",
      _drummer: "Jeff Saunders",
      _weight: "70.0",
      _preference: "None",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Jit",
      _surname: "Lim",
      _gender: "M",
      _fullName: "Jit Lim",
      _left: "Jit Lim",
      _right: "Jit Lim",
      _sweep: "",
      _drummer: "",
      _weight: "100.0",
      _preference: "None",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Joe",
      _surname: "Gomory",
      _gender: "M",
      _fullName: "Joe Gomory",
      _left: "Joe Gomory",
      _right: "Joe Gomory",
      _sweep: "",
      _drummer: "",
      _weight: "",
      _preference: "_right",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "John",
      _surname: "Moffat",
      _gender: "M",
      _fullName: "John Moffat",
      _left: "John Moffat",
      _right: "John Moffat",
      _sweep: "",
      _drummer: "",
      _weight: "112.0",
      _preference: "_right",
      _division: "B",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "John",
      _surname: "Robinson",
      _gender: "M",
      _fullName: "John Robinson",
      _left: "John Robinson",
      _right: "John Robinson",
      _sweep: "",
      _drummer: "",
      _weight: "76.7",
      _preference: "_left",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Kamal",
      _surname: "Baidawi",
      _gender: "M",
      _fullName: "Kamal Baidawi",
      _left: "Kamal Baidawi",
      _right: "Kamal Baidawi",
      _sweep: "",
      _drummer: "",
      _weight: "80.5",
      _preference: "None",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Mark",
      _surname: "Hammond",
      _gender: "M",
      _fullName: "Mark Hammond",
      _left: "Mark Hammond",
      _right: "Mark Hammond",
      _sweep: "",
      _drummer: "",
      _weight: "",
      _preference: "_right",
      _division: "B",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Mark",
      _surname: "van Tatenhove",
      _gender: "M",
      _fullName: "Mark van Tatenhove",
      _left: "Mark van Tatenhove",
      _right: "Mark van Tatenhove",
      _sweep: "",
      _drummer: "",
      _weight: "91.0",
      _preference: "_left",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Mark",
      _surname: "Wood",
      _gender: "M",
      _fullName: "Mark Wood",
      _left: "Mark Wood",
      _right: "Mark Wood",
      _sweep: "",
      _drummer: "",
      _weight: "70.0",
      _preference: "_right",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Mike",
      _surname: "Lee",
      _gender: "M",
      _fullName: "Mike Lee",
      _left: "Mike Lee",
      _right: "Mike Lee",
      _sweep: "",
      _drummer: "",
      _weight: "115.0",
      _preference: "_right",
      _division: "B",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "1",
      _sweepOrDrummerRaces: "0",
      _paddling: "1",
      Reserve: ""
    },
    {
      _firstName: "Mike",
      _surname: "McGenniskin",
      _gender: "M",
      _fullName: "Mike McGenniskin",
      _left: "Mike McGenniskin",
      _right: "Mike McGenniskin",
      _sweep: "Mike McGenniskin",
      _drummer: "",
      _weight: "83.8",
      _preference: "_right",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "1",
      _sweepOrDrummerRaces: "1",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Paul",
      _surname: "Driver",
      _gender: "M",
      _fullName: "Paul Driver",
      _left: "Paul Driver",
      _right: "Paul Driver",
      _sweep: "",
      _drummer: "",
      _weight: "89.6",
      _preference: "_right",
      _division: "B",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Paul",
      _surname: "Shannon",
      _gender: "M",
      _fullName: "Paul Shannon",
      _left: "Paul Shannon",
      _right: "Paul Shannon",
      _sweep: "Paul Shannon",
      _drummer: "",
      _weight: "75.0",
      _preference: "_left",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Richard",
      _surname: "Chan",
      _gender: "M",
      _fullName: "Richard Chan",
      _left: "Richard Chan",
      _right: "Richard Chan",
      _sweep: "",
      _drummer: "",
      _weight: "71.8",
      _preference: "None",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Rob",
      _surname: "Stewart",
      _gender: "M",
      _fullName: "Rob Stewart",
      _left: "Rob Stewart",
      _right: "Rob Stewart",
      _sweep: "Rob Stewart",
      _drummer: "",
      _weight: "75.0",
      _preference: "_right",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Ross",
      _surname: "Parker",
      _gender: "M",
      _fullName: "Ross Parker",
      _left: "Ross Parker",
      _right: "Ross Parker",
      _sweep: "Ross Parker",
      _drummer: "",
      _weight: "81.8",
      _preference: "None",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Sam",
      _surname: "Donato",
      _gender: "M",
      _fullName: "Sam Donato",
      _left: "Sam Donato",
      _right: "Sam Donato",
      _sweep: "",
      _drummer: "",
      _weight: "100.0",
      _preference: "None",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "1",
      _sweepOrDrummerRaces: "0",
      _paddling: "1",
      Reserve: ""
    },
    {
      _firstName: "Stephen",
      _surname: "Arrowsmith",
      _gender: "M",
      _fullName: "Stephen Arrowsmith",
      _left: "Stephen Arrowsmith",
      _right: "Stephen Arrowsmith",
      _sweep: "",
      _drummer: "",
      _weight: "114.0",
      _preference: "None",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Steve",
      _surname: "Kaplan",
      _gender: "M",
      _fullName: "Steve Kaplan",
      _left: "Steve Kaplan",
      _right: "Steve Kaplan",
      _sweep: "",
      _drummer: "",
      _weight: "114.0",
      _preference: "None",
      _division: "B",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Victor",
      _surname: "Usher",
      _gender: "M",
      _fullName: "Victor Usher",
      _left: "Victor Usher",
      _right: "Victor Usher",
      _sweep: "",
      _drummer: "",
      _weight: "83.3",
      _preference: "_right",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    },
    {
      _firstName: "Wayne",
      _surname: "Chappel",
      _gender: "M",
      _fullName: "Wayne Chappel",
      _left: "Wayne Chappel",
      _right: "Wayne Chappel",
      _sweep: "",
      _drummer: "",
      _weight: "86.6",
      _preference: "_left",
      _division: "C",
      _gender: "M",
      Regatta: "Yes",
      Men: "Yes",
      Women: " ",
      _noOfRaces: "0",
      _sweepOrDrummerRaces: "0",
      _paddling: "0",
      Reserve: ""
    }
]

let newData = data;
for (let i = 0; i < data.length; i++) {
//if memeber is left
if (data[i]._left.length > 0) {
    newData[i]._left = "Yes"
} else {
    newData[i]._left = "No"
}
//if member is right
if (data[i]._right.length > 0) {
    newData[i]._right = "Yes"
} else {
    newData[i]._right = "No"
}
//if member has a preference
if (data[i]._preference == "_left") {
    newData[i]._preference = "left"
} else if (data[i]._preference == "_right") {
    newData[i]._preference = "right"
} else {
    newData[i]._preference = "None"
}
//if member can be a sweep
if (data[i]._sweep.length > 0) {
    newData[i]._sweep = "Yes"
} else {
    newData[i]._sweep = "No"
}
//if member can be a drummer
if (data[i]._drummer.length > 0) {
    newData[i]._drummer = "Yes"
} else {
    newData[i]._drummer = "No"
}

delete newData[i]._fullName
delete newData[i].Regatta
delete newData[i].Men
delete newData[i].Women
delete newData[i]._paddling
delete newData[i].Reserve
}

setLocalStorage(KEY_MEMBERS, newData)

